app/Http/routes.php
<?php

// Authorization
Route::get('/login', ['as' => 'auth.login.form', 'uses' => 'Auth\SessionController@getLogin']);
Route::post('/login', ['as' => 'auth.login.attempt', 'uses' => 'Auth\SessionController@postLogin']);
Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\SessionController@getLogout']);

// Users
Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('/pages', 'PageController');

Route::get('/', ['as' => 'index', 'uses' => 'PageController@dashboard']);

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
         'email', 'password', 'first_name', 'last_name',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];

    public function roles() {
        return $this->belongsToMany('App\Role');       
    }

    public function pages()
    {
        return $this->hasMany('App\Page');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Sentinel;
use Activation;

class UserController extends Controller
{
    protected $userRepository;

    public function __construct()
    {
        // Middleware
        $this->middleware('sentinel.auth');
        $this->middleware('sentinel.access:users.create', ['only' => ['create', 'store']]);
        $this->middleware('sentinel.access:users.view', ['only' => ['index', 'show']]);
        $this->middleware('sentinel.access:users.update', ['only' => ['edit', 'update']]);
        $this->middleware('sentinel.access:users.destroy', ['only' => ['destroy']]);
        $this->userRepository = app()->make('sentinel.users');
    }

    public function index()
    {
        $users = $this->userRepository->createModel()->get();
        return view('Centaur::users.index', ['users' => $users]);
    } 

    public function create()
    {
        $roles = app()->make('sentinel.roles')->createModel()->all();
        return view('Centaur::users.create', ['roles' => $roles]);
    }

    public function store(Request $request)
    {
        $result = $this->validate($request, [
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|confirmed|min:6'
        ]);
        $userArray = [
            'email' => trim($request->get('email')),
            'password' => $request->get('password'),
            'first_name' => $request->get('first_name', null),
            'last_name' => $request->get('last_name', null),
        ];

        $user = Sentinel::getUserRepository()->create($userArray);

        $code = Activation::create($user)->code;
        Activation::complete($user, $code);

        foreach ($request->get('roles', []) as $slug => $id) {
            $role = Sentinel::findRoleBySlug($slug);
            if ($role) {
                $role->users()->attach($user);
            }
        }

        session()->flash("success", "User {$request->get('email')} has been created.");
        return redirect('/users');
    }

    public function edit($id)
    {
        $user = $this->userRepository->findById($id);

        // Fetch the available roles
        $roles = app()->make('sentinel.roles')->createModel()->all();
         
        if ($user) {
            return view('Centaur::users.edit', [
                'user' => $user,
                'roles' => $roles,
            ]);
        }

        session()->flash('error', 'Invalid user.');
        return redirect()->back();
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'password' => 'confirmed|min:6',
        ]);

        $attributes = [
            'email' => trim($request->get('email')),
            'first_name' => $request->get('first_name', null),
            'last_name' => $request->get('last_name', null)
        ];

        if ($request->has('password')) {
            $attributes['password'] = $request->get('password');
        }
        
        $user = $this->userRepository->findById($id);
        if (!$user) {
            session()->flash('error', 'Invalid user.');
            return redirect()->back()->withInput();
        }
        $user = $this->userRepository->update($user, $attributes);
        $roleIds = array_values($request->get('roles', []));
        $user->roles()->sync($roleIds);

        session()->flash('success', "{$user->email} ažuriran.");
        return redirect()->route('users.index');
    }

    public function destroy($id)
    {
        $user = $this->userRepository->findById($id);
        if (Sentinel::getUser()->id == $user->id) {
            $message = "You cannot remove yourself!";
            session()->flash('error', $message);
            return redirect()->route('users.index');
        }
        $user->delete();
        $message = "{$user->email} has been removed.";

        session()->flash('success', $message);
        return redirect()->route('users.index');
    }
}

resources/views/centaur/users/create.blade.php
@extends('Centaur::layout')

@section('title', 'Create New User')

@section('content')
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Kreiranje novog korisnika</h3>
            </div>
            <div class="panel-body">
                <form accept-charset="UTF-8" role="form" method="post" action="{{ route('users.store') }}">
                <fieldset>
                    <div class="form-group {{ ($errors->has('first_name')) ? 'has-error' : '' }}">
                        <input class="form-control" placeholder="First Name" name="first_name" type="text" value="{{ old('first_name') }}" />
                        {!! ($errors->has('first_name') ? $errors->first('first_name', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('last_name')) ? 'has-error' : '' }}">
                        <input class="form-control" placeholder="Last Name" name="last_name" type="text" value="{{ old('last_name') }}" />
                        {!! ($errors->has('last_name') ? $errors->first('last_name', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('email')) ? 'has-error' : '' }}">
                        <input class="form-control" placeholder="E-mail" name="email" type="text" value="{{ old('email') }}">
                        {!! ($errors->has('email') ? $errors->first('email', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <h5>Roles</h5>
                    @foreach ($roles as $role)
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="roles[{{ $role->slug }}]" value="{{ $role->id }}">
                                {{ $role->name }}
                            </label>
                        </div>
                    @endforeach
                    <hr />
                    <div class="form-group  {{ ($errors->has('password')) ? 'has-error' : '' }}">
                        <input class="form-control" placeholder="Password" name="password" type="password" value="">
                        {!! ($errors->has('password') ? $errors->first('password', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('password_confirmation')) ? 'has-error' : '' }}">
                        <input class="form-control" placeholder="Confirm Password" name="password_confirmation" type="password" />
                        {!! ($errors->has('password_confirmation') ? $errors->first('password_confirmation', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <input name="_token" value="{{ csrf_token() }}" type="hidden">
                    <input class="btn btn-lg btn-primary btn-block" type="submit" value="Kreiraj">
                </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/centaur/users/edit.blade.php
@extends('Centaur::layout')
@section('title', 'Edit User')
@section('content')
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Uređivanje korisnika</h3>
            </div>
            <div class="panel-body">
                <form accept-charset="UTF-8" role="form" method="post" action="{{ route('users.update', $user->id) }}">
                    <fieldset>
                        <div class="form-group {{ ($errors->has('first_name')) ? 'has-error' : '' }}">
                            <input class="form-control" placeholder="First Name" name="first_name" type="text" value="{{ $user->first_name }}"/>
                            {!! ($errors->has('first_name') ? $errors->first('first_name', '<p class="text-danger">:message</p>') : '') !!}
                        </div>
                        <div class="form-group {{ ($errors->has('last_name')) ? 'has-error' : '' }}">
                            <input class="form-control" placeholder="Last Name" name="last_name" type="text" value="{{ $user->last_name }}"/>
                            {!! ($errors->has('last_name') ? $errors->first('last_name', '<p class="text-danger">:message</p>') : '') !!}
                        </div>
                        <div class="form-group {{ ($errors->has('email')) ? 'has-error' : '' }}">
                            <input class="form-control" placeholder="E-mail" name="email" type="text" value="{{ $user->email }}">
                            {!! ($errors->has('email') ? $errors->first('email', '<p class="text-danger">:message</p>') : '') !!}
                        </div>
                        <h5>Grupe:</h5>
                        @foreach ($roles as $role)
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="roles[{{ $role->slug }}]" value="{{ $role->id }}" {{ $user->inRole($role->slug) ? 'checked' : '' }}>
                                {{ $role->name }}
                            </label>
                        </div>
                        @endforeach
                        <hr/>
                        <div class="form-group  {{ ($errors->has('password')) ? 'has-error' : '' }}">
                            <input class="form-control" placeholder="Password" name="password" type="password" value="">
                            {!! ($errors->has('password') ? $errors->first('password', '<p class="text-danger">:message</p>') : '') !!}
                        </div>
                        <div class="form-group {{ ($errors->has('password_confirmation')) ? 'has-error' : '' }}">
                            <input class="form-control" placeholder="Confirm Password" name="password_confirmation" type="password" value="{{ old('password_confirmation') }}"/>
                            {!! ($errors->has('password_confirmation') ? $errors->first('password_confirmation', '<p class="text-danger">:message</p>') : '') !!}
                        </div>
                        <input name="_token" value="{{ csrf_token() }}" type="hidden">
                        <input name="_method" value="PUT" type="hidden">
                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Ažuriraj">
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/centaur/users/index.blade.php
@extends('Centaur::layout')
@section('title', 'Users')
@section('content')

<div class="page-header">
    <div class="container" style="text-align: center;">
        
        <div class="row">
           
             

<div class='btn-toolbar pull-right'>
           <a href="{{ route('users.create') }}" class="btn btn-primary"> Dodaj korisnika </a>
        </div>
        <h1 style=" text-align:left">Korisnici</h1>
        




            <div class = "panel panel-primary filterable">
                <div class="panel-heading">
                    <center><h3 class="panel-title" style="color:white"><strong>Lista svih korisnika </strong></h3> </center>
                    
                    <div class="pull-right">
                        <button class="btn btn-default btn-xs btn-filter"><span style="margin-right: 10px;" class="glyphicon glyphicon-filter"> </span>Filter </button>
                    </div>
                </div>
                <table id="datatable" class="table table-hover" cellspacing="0" style=" background-color: white;">
                    <thead>
                        <?php $t = 1; ?>
                        <tr class = "filters" >
                            <th><input type = "text" class = "form-control" placeholder = "Rbr." disabled style = "text-align: center;"></th>
                            <th><input type = "text" class = "form-control" placeholder = "Ime i Prezime" disabled style = "text-align: center;"></th>
                            <th><input type = "text" class = "form-control" placeholder = "Razina prava" disabled style = "text-align: center;"></th>
                            <th><input type = "text" class = "form-control" placeholder = "Mogućnosti" disabled style = "text-align: center;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                        <tr>
                            <td> {{ $t++}}.  </td>
                            @if (!empty($user->first_name . $user->last_name))
                            <td><strong> {{ $user->first_name . ' ' . $user->last_name}} </strong></td>
                            @else
                            <td>(nema upisanog imena)</td>
                            @endif
                            <td> <strong>  @if ($user->roles)
                                    @if ($user->roles->count() > 0)
                                    {{ $user->roles->implode('name', ', ') }}
                                    @else
                                    <em class="label label-danger">Nema prava</em>
                                    @endif
                                    @endif
                                </strong>
                            </td>
                            <td>
                                <a href="{{ route('users.edit', $user->id) }}" class="btn btn-xs btn-info"> <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Uredi </a>
                                <a href="{{ route('users.destroy', $user->id) }}" class="btn btn-xs btn-danger" data-method="delete" data-token="{{ csrf_token() }}"> <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Obriši </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>             
            </div>
        </div>
    </div>
    
</div>
@endsection
@section('afterbody')
<script src="{{ url('/theme/js/jquery-3.1.1.min.js') }}"></script>
<script>
/*
 Please consider that the JS part isn't production ready at all, I just code it to show the concept of merging filters and titles together !
 */
$(document).ready(function () {
    $('.filterable .btn-filter').click(function () {
        var $panel = $(this).parents('.filterable'),
                $filters = $panel.find('.filters input'),
                $tbody = $panel.find('.table tbody');
        if ($filters.prop('disabled') == true) {
            $filters.prop('disabled', false);
            $filters.first().focus();
        } else {
            $filters.val('').prop('disabled', true);
            $tbody.find('.no-result').remove();
            $tbody.find('tr').show();
        }
    });

    $('.filterable .filters input').keyup(function (e) {
        /* Ignore tab key */
        var code = e.keyCode || e.which;
        if (code == '9')
            return;
        /* Useful DOM data and selectors */
        var $input = $(this),
                inputContent = $input.val().toLowerCase(),
                $panel = $input.parents('.filterable'),
                column = $panel.find('.filters th').index($input.parents('th')),
                $table = $panel.find('.table'),
                $rows = $table.find('tbody tr');
        /* Dirtiest filter function ever ;) */
        var $filteredRows = $rows.filter(function () {
            var value = $(this).find('td').eq(column).text().toLowerCase();
            return value.indexOf(inputContent) === -1;
        });
        /* Clean previous no-result if exist */
        $table.find('tbody .no-result').remove();
        /* Show all rows, hide filtered ones (never do that outside of a demo ! xD) */
        $rows.show();
        $filteredRows.hide();
        /* Prepend no-result row if all rows are filtered */
        if ($filteredRows.length === $rows.length) {
            $table.find('tbody').prepend($('<tr class="no-result text-center"><td colspan="' + $table.find('.filters th').length + '">No result found</td></tr>'));
        }
    });
});

</script>
@endsection